In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Series

In [2]:
pd.Series()

Series([], dtype: object)

In [3]:
liste = [1,2,3,4,5]

In [4]:
seri = pd.Series(liste)
seri

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
type(seri)

pandas.core.series.Series

In [6]:
seri.dtype

dtype('int64')

In [7]:
arr = np.array([1,2,5.6,'array'])
arr

array(['1', '2', '5.6', 'array'], dtype='<U32')

In [9]:
seri = pd.Series([1,2,5.6,'array'])
seri

0        1
1        2
2      5.6
3    array
dtype: object

In [10]:
seri.apply(type)

0      <class 'int'>
1      <class 'int'>
2    <class 'float'>
3      <class 'str'>
dtype: object

In [12]:
seri = pd.Series([1,2,3.7,8.9]).astype(int)
seri

0    1
1    2
2    3
3    8
dtype: int64

In [13]:
seri2 = pd.Series([1,2,3.7,8.9], dtype = 'int32')
seri2 # veri kaybı olacağı için hata verir

ValueError: Trying to coerce float values to integers

In [14]:
seri3 = pd.Series([1,2,3.7,8.9], dtype = str)
seri3

0      1
1      2
2    3.7
3    8.9
dtype: object

In [15]:
seri4 = pd.Series([1,2,3.7,8.9], dtype = float)
seri4

0    1.0
1    2.0
2    3.7
3    8.9
dtype: float64

In [16]:
seri4 = pd.Series([1,2,3.7,8.9])
seri4

0    1.0
1    2.0
2    3.7
3    8.9
dtype: float64

In [18]:
seri = pd.Series([1,2,3],dtype = int)
seri

0    1
1    2
2    3
dtype: int64

In [19]:
seri = pd.Series(data = liste,index = ['a','b','c','d','e'])
seri

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [20]:
seri = pd.Series(data = liste,index = ['a','b','c','d','e','f'])
seri # verdiğimiz index sayisi daha fazla

ValueError: Length of values (5) does not match length of index (6)

In [ ]:
# Numpy arrays

In [21]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
seri = pd.Series(data = arr)
seri # array direk içine yazamayız

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 3) instead

In [23]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [25]:
seri = pd.Series(arr1)
seri # 1. yöntem 

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [26]:
seri = pd.Series(np.arange(5))
seri # 2. yöntem

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [27]:
seri = pd.Series(np.arange(10,50,10), index = [1,2,3,4])
seri

1    10
2    20
3    30
4    40
dtype: int64

In [28]:
seri = pd.Series(np.arange(10,50,10), index = np.arange(1,5))
seri

1    10
2    20
3    30
4    40
dtype: int64

In [29]:
seri = pd.Series(np.arange(10,50,10), index = ['1','2','3','4'])
seri # index i hem tuple hemde liste içinde yazabiliriz

1    10
2    20
3    30
4    40
dtype: int64

In [30]:
seri = pd.Series(np.arange(10,50,10), index = ('1','2','3','4'))
seri # index i hem tuple hemde liste içinde yazabiliriz

1    10
2    20
3    30
4    40
dtype: int64

In [31]:
seri = pd.Series(np.arange(10,50,10), index = (1,2,3,4))
seri

1    10
2    20
3    30
4    40
dtype: int64

In [ ]:
# Numpy dict

In [32]:
dict = { 'resim' : 75, 'fen' : 90, 'mat' : 80}

In [33]:
seri = pd.Series(dict)
seri

resim    75
fen      90
mat      80
dtype: int64

In [36]:
seri_new = pd.Series(dict, index = ['resim','müzik','mat'])
seri_new
# NaN değerden dolayı dtype : float oldu
# müzik key dict içinde olmadığı için NaN değer döndürdü.

resim    75.0
müzik     NaN
mat      80.0
dtype: float64

In [37]:
seri_new = pd.Series(dict, index = ['resim','müzik','mat','fen'])
seri_new
# NaN değerden dolayı dtype : float oldu
# müzik key dict içinde olmadığı için NaN değer döndürdü.

resim    75.0
müzik     NaN
mat      80.0
fen      90.0
dtype: float64

In [38]:
seri_new = pd.Series(dict, index = ['resim','müzik','mat','tarih'])
seri_new
# NaN değerden dolayı dtype : float oldu
# müzik key dict içinde olmadığı için NaN değer döndürdü.

resim    75.0
müzik     NaN
mat      80.0
tarih     NaN
dtype: float64

In [39]:
seri_new = pd.Series(dict, index = ['resim','müzik','mat','fen','resim'])
seri_new
# NaN değerden dolayı dtype : float oldu
# müzik key dict içinde olmadığı için NaN değer döndürdü.

resim    75.0
müzik     NaN
mat      80.0
fen      90.0
resim    75.0
dtype: float64

In [ ]:
#scalar value

In [40]:
pd.Series([10])

0    10
dtype: int64

In [41]:
pd.Series(10, index = [1,2,3])

1    10
2    10
3    10
dtype: int64

In [43]:
pd.Series('pandas')

0    pandas
dtype: object

In [44]:
#Concat

In [45]:
dict

{'resim': 75, 'fen': 90, 'mat': 80}

In [46]:
seri = pd.Series(dict,index = ('x','fen','mat'))
seri

x       NaN
fen    90.0
mat    80.0
dtype: float64

In [47]:
seri2 = pd.concat((seri,seri)) # tuple olarak yazabiliriz
seri2

x       NaN
fen    90.0
mat    80.0
x       NaN
fen    90.0
mat    80.0
dtype: float64

In [48]:
seri2 = pd.concat([seri,seri]) # list olarak yazabiliriz
seri2

x       NaN
fen    90.0
mat    80.0
x       NaN
fen    90.0
mat    80.0
dtype: float64

In [49]:
x = pd.Series([356,357,358])
y = pd.Series(['ahmet','veli','mehmet','mustafa'])
pd.concat((x,y))

0        356
1        357
2        358
0      ahmet
1       veli
2     mehmet
3    mustafa
dtype: object

In [52]:
x = pd.Series([356,357,358])
y = pd.Series(['ahmet','veli','mehmet','mustafa'])
pd.concat((x,y),axis = 1)

0        1
0  356.0    ahmet
1  357.0     veli
2  358.0   mehmet
3    NaN  mustafa

In [ ]:
# indexing ve slicing with pandas serileri

In [53]:
seri = pd.Series([1,2,3,4],index = ["python","git","numpy","pandas"])
seri

python    1
git       2
numpy     3
pandas    4
dtype: int64

In [54]:
seri[3]

np.int64(4)

In [55]:
seri['pandas']

np.int64(4)

In [56]:
seri.index[3]

'pandas'

In [57]:
seri[2]

np.int64(3)

In [58]:
seri[2:]

numpy     3
pandas    4
dtype: int64

In [59]:
seri

python    1
git       2
numpy     3
pandas    4
dtype: int64

In [60]:
seri[1:3]

git      2
numpy    3
dtype: int64

In [62]:
seri[[0,3]] # birden fazla elemanı alırken parantez yazarız

python    1
pandas    4
dtype: int64

In [63]:
seri['git'] # tek parantez ile sadece value dönerken

np.int64(2)

In [64]:
seri[['git']] # tek parantez ile sadece value dönerken

git    2
dtype: int64

In [66]:
seri[['git','pandas']]

git       2
pandas    4
dtype: int64

In [68]:
seri['git':'pandas']
# index label ile slicing yaparken bitiş noktası olan index index label da dahil edilir

git       2
numpy     3
pandas    4
dtype: int64

In [69]:
seri

python    1
git       2
numpy     3
pandas    4
dtype: int64

In [70]:
seri[[0,3,2]]

python    1
pandas    4
numpy     3
dtype: int64

In [71]:
seri[::-1]

pandas    4
numpy     3
git       2
python    1
dtype: int64

In [ ]:
# basic attributes ve methods of series

In [72]:
np.random.seed(42)
seri = pd.Series(np.random.randint(0,50,6))
seri

0    38
1    28
2    14
3    42
4     7
5    20
dtype: int32

In [73]:
seri.dtype

dtype('int32')

In [74]:
seri.apply(type)

0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
dtype: object

In [75]:
seri.size

6

In [76]:
seri.ndim

1

In [77]:
seri.index

RangeIndex(start=0, stop=6, step=1)

In [79]:
seri.values

array([38, 28, 14, 42,  7, 20], dtype=int32)

In [78]:
seri.items

<bound method Series.items of 0    38
1    28
2    14
3    42
4     7
5    20
dtype: int32>

In [82]:
list(seri.items())

[(0, 38), (1, 28), (2, 14), (3, 42), (4, 7), (5, 20)]

In [83]:
seri.head() # default ilk 5 değeri döndürdü

0    38
1    28
2    14
3    42
4     7
dtype: int32

In [84]:
seri.head(2)

0    38
1    28
dtype: int32

In [85]:
seri.tail() # default son 5 değeri döndürdü

1    28
2    14
3    42
4     7
5    20
dtype: int32

In [86]:
seri.tail(2)

4     7
5    20
dtype: int32

In [87]:
seri.sample() # rastgele 1 değer döndürdü

5    20
dtype: int32

In [88]:
seri.sample(3)

0    38
1    28
2    14
dtype: int32

In [90]:
seri.sort_index(ascending = True) # default

0    38
1    28
2    14
3    42
4     7
5    20
dtype: int32

In [91]:
seri.sort_index(ascending = False)

5    20
4     7
3    42
2    14
1    28
0    38
dtype: int32

In [92]:
seri.sort_values() #default ascending = True

4     7
2    14
5    20
1    28
0    38
3    42
dtype: int32

In [94]:
seri.sort_values(ascending = False)

3    42
0    38
1    28
5    20
2    14
4     7
dtype: int32

In [95]:
seri.sort_values(ascending = 0)

3    42
0    38
1    28
5    20
2    14
4     7
dtype: int32

In [96]:
seri.sort_values(ascending = 1)

4     7
2    14
5    20
1    28
0    38
3    42
dtype: int32

In [97]:
car_brands = ['Toyota', 'Ford', 'BMW', 'Mercedes', 'Audi', 'Tesla', 'Honda', 'Nissan', 'Chevrolet', 'Hyundai']
seri = pd.Series(car_brands)
seri

0       Toyota
1         Ford
2          BMW
3     Mercedes
4         Audi
5        Tesla
6        Honda
7       Nissan
8    Chevrolet
9      Hyundai
dtype: object

In [98]:
seri.isin(['Toyota','Ford']) # True ve False araması yaptık

0     True
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [100]:
seri[seri.isin(['Toyota','Ford'])]

0    Toyota
1      Ford
dtype: object

In [101]:
seri.isin([100,200])

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [102]:
seri[seri.isin([100,200])]

Series([], dtype: object)

In [ ]:
# DataFrames